CREATE TABLE tb_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(50)                             NOT NULL,
    last_name  VARCHAR(100)                            NOT NULL,
    email      VARCHAR(100)                            NOT NULL,
    phone      VARCHAR(14),
    password   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_user PRIMARY KEY (id)
);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_email UNIQUE (email);