CREATE TABLE tb_category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_tb_category PRIMARY KEY (id)
);

ALTER TABLE tb_category
    ADD CONSTRAINT uc_tb_category_name UNIQUE (name);