CREATE TABLE tb_order
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    moment       TIMESTAMP WITHOUT TIME ZONE,
    order_status INTEGER                                 NOT NULL,
    client_id    BIGINT,
    CONSTRAINT pk_tb_order PRIMARY KEY (id)
);

ALTER TABLE tb_order
    ADD CONSTRAINT FK_TB_ORDER_ON_CLIENT FOREIGN KEY (client_id) REFERENCES tb_user (id);